# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'bookStore.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

import sqlite3
db = sqlite3.connect('store.db')
cursor = db.cursor()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btn1 = QtWidgets.QPushButton(self.centralwidget)
        self.btn1.setGeometry(QtCore.QRect(610, 120, 141, 31))
        self.btn1.setStyleSheet("font: 75 14pt \"Comic Sans MS\";\n"
"background-color: rgb(185, 185, 185);\n"
" ")
        self.btn1.setObjectName("btn1")
        self.t1 = QtWidgets.QLineEdit(self.centralwidget)
        self.t1.setGeometry(QtCore.QRect(240, 110, 331, 41))
        self.t1.setStyleSheet(" \n"
"border-color: rgb(26, 26, 26);\n"
"font: 14pt \"Comic Sans MS\";")
        self.t1.setObjectName("t1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(80, 110, 131, 51))
        self.label.setStyleSheet("font: 75 14pt \"Comic Sans MS\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(140, 180, 71, 51))
        self.label_2.setStyleSheet("font: 75 14pt \"Comic Sans MS\";")
        self.label_2.setObjectName("label_2")
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setGeometry(QtCore.QRect(150, 250, 611, 20))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 330, 111, 41))
        self.label_3.setStyleSheet("font: 75 14pt \"Comic Sans MS\";\n"
"font: 75 14pt \"Comic Sans MS\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(130, 400, 81, 51))
        self.label_4.setStyleSheet("font: 75 14pt \"Comic Sans MS\";")
        self.label_4.setObjectName("label_4")
        self.btn2 = QtWidgets.QPushButton(self.centralwidget)
        self.btn2.setGeometry(QtCore.QRect(620, 340, 141, 31))
        self.btn2.setStyleSheet("font: 75 14pt \"Comic Sans MS\",rgb(176, 176, 176);\n"
"background-color: rgb(185, 185, 185);\n"
"")
        self.btn2.setObjectName("btn2")
        self.t3 = QtWidgets.QLineEdit(self.centralwidget)
        self.t3.setGeometry(QtCore.QRect(240, 330, 331, 41))
        self.t3.setStyleSheet(" \n"
"border-color: rgb(26, 26, 26);\n"
"font: 14pt \"Comic Sans MS\";")
        self.t3.setObjectName("t3")
        self.t2 = QtWidgets.QLineEdit(self.centralwidget)
        self.t2.setGeometry(QtCore.QRect(240, 190, 111, 31))
        self.t2.setStyleSheet("color: rgb(24, 16, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.t2.setObjectName("t2")
        self.t4 = QtWidgets.QLineEdit(self.centralwidget)
        self.t4.setGeometry(QtCore.QRect(240, 410, 111, 31))
        self.t4.setStyleSheet("color: rgb(24, 16, 255);\n"
"font: 14pt \"MS Shell Dlg 2\";")
        self.t4.setObjectName("t4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.btn1.clicked.connect(self.FindPrice)
        self.btn2.clicked.connect(self.TotalPrice)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Window Title"))
        self.label.setText(_translate("MainWindow", "Book Title:"))
        self.label_3.setText(_translate("MainWindow", "Quantity:"))
        self.label_2.setText(_translate("MainWindow", "Price :"))
        self.t1.setPlaceholderText(_translate("MainWindow", "text"))
        self.t3.setPlaceholderText(_translate("MainWindow", "text"))
        self.label_4.setText(_translate("MainWindow", "Total :"))
        self.t2.setText(_translate("MainWindow", "Rs. 0"))
        self.t2.setPlaceholderText(_translate("MainWindow", "text"))
        self.t4.setText(_translate("MainWindow", "Rs. 0"))
        self.t4.setPlaceholderText(_translate("MainWindow", "text"))
        self.btn1.setText(_translate("MainWindow", "Find Price"))
        self.btn2.setText(_translate("MainWindow", "Find Total"))

    def FindPrice(self):
        bookName=self.t1.text().title()
        self.t3.setText("1")
        cursor.execute(f""" SELECT Price FROM STORE WHERE Book_Name = '{bookName}';""")
        price=cursor.fetchone()[0]
        self.t2.setText("Rs. "+str(price))
        self.t4.setText("Rs. "+str(price))


    def TotalPrice(self):
        bookName=self.t1.text().title()
        cursor.execute(f""" SELECT Price FROM STORE WHERE Book_Name = '{bookName}';""")
        price=cursor.fetchone()[0]
        totalBooks=int(self.t3.text())
        total=totalBooks*price
        self.t4.setText("Rs. "+str(total))
 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
